test_0 (__main__.lab6a.test_0)
[Lab 6] - [Investigation 1] - [Part 2] - Creating Classes - Test for file creation: ./lab6a.py ... ok
test_a (__main__.lab6a.test_a)
[Lab 6] - [Investigation 1] - [Part 2] - Creating a Class - Test for errors running: ./lab6a.py ... ok
test_a1 (__main__.lab6a.test_a1)
[Lab 6] - [Investigation 1] - [Part 2] - Creating Classes - Test for correct shebang line: ./lab6a.py ... ok
test_a_instantiate_class_0 (__main__.lab6a.test_a_instantiate_class_0)
[Lab 6] - [Investigation 1] - [Part 2] - Creating Classes - instantiating object with 0 arguments fails ... ok
test_a_instantiate_class_1 (__main__.lab6a.test_a_instantiate_class_1)
[Lab 6] - [Investigation 1] - [Part 2] - Creating Classes - instantiating object with 1 arguments fails ... ok
test_b1_displayStudent (__main__.lab6a.test_b1_displayStudent)
[Lab 6] - [Investigation 1] - [Part 2] - Creating Classes - displayStudent() provides the correct output ... ok
test_b2_displayStudent (__main__.lab6a.test_b2_displayStudent)
[Lab 6] - [Investigation 1] - [Part 2] - Creating Classes - displayStudent() does not fail if self.number is an integer ... ok
test_c_displayStudent (__main__.lab6a.test_c_displayStudent)
[Lab 6] - [Investigation 1] - [Part 2] - Creating Classes - displayStudent() does not fail if self.number is an integer ... ok
test_d_displayGPA (__main__.lab6a.test_d_displayGPA)
[Lab 6] - [Investigation 1] - [Part 2] - Creating Classes - displayGPA() provides the correct output ... ok
test_e_displayGPA (__main__.lab6a.test_e_displayGPA)
[Lab 6] - [Investigation 1] - [Part 2] - Creating Classes - displayGPA() handles ZeroDivisionError successfully ... ok
test_f_displayGPA (__main__.lab6a.test_f_displayGPA)
[Lab 6] - [Investigation 1] - [Part 2] - Creating Classes - displayGPA() handles ZeroDivisionError successfully ... ok
test_g1_displayCourses (__main__.lab6a.test_g1_displayCourses)
[Lab 6] - [Investigation 1] - [Part 2] - Creating Classes - displayCourses() provides the correct output ... ok
test_g2_displayCourses (__main__.lab6a.test_g2_displayCourses)
[Lab 6] - [Investigation 1] - [Part 2] - Creating Classes - displayCourses() provides the correct output ... FAIL
test_h_displayCourses (__main__.lab6a.test_h_displayCourses)
[Lab 6] - [Investigation 1] - [Part 2] - Creating Classes - displayCourses() provides the correct output ... FAIL

======================================================================
FAIL: test_g2_displayCourses (__main__.lab6a.test_g2_displayCourses)
[Lab 6] - [Investigation 1] - [Part 2] - Creating Classes - displayCourses() provides the correct output
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jdannuy/ops445/lab6/./CheckLab6.py", line 175, in test_g2_displayCourses
    self.assertEqual(string1, answer, msg=error_output)
AssertionError: Items in the first set but not the second:
'p'
'1'
'0'
'5'
'o'
'l'
'2'
'3'
'i'
'u'
's'
' '
Items in the second set but not the first:
'uli101'
'ops235' : your program has an error(HINT: does not have correct output)

======================================================================
FAIL: test_h_displayCourses (__main__.lab6a.test_h_displayCourses)
[Lab 6] - [Investigation 1] - [Part 2] - Creating Classes - displayCourses() provides the correct output
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jdannuy/ops445/lab6/./CheckLab6.py", line 192, in test_h_displayCourses
    self.assertEqual(string1, answer, msg=error_output)
AssertionError: Items in the first set but not the second:
'p'
'1'
'4'
'0'
'5'
'o'
'l'
'c'
'3'
'i'
'u'
's'
' '
Items in the second set but not the first:
'ops535'
'uli101' : your program has an error(HINT: does not have correct output)

----------------------------------------------------------------------
Ran 14 tests in 0.031s

FAILED (failures=2)
